#!/bin/dash

#colors="-nb #ede1d4 -nf #423F3D -sb #423f3d -sf #f4ede6" 
colors="-nb #353535 -nf #ede1d4 -sb #e2a76d -sf #353535"

res=$(xrandr --nograb --current | awk '/\*/ {print $1}' | tail -n 1)
res=${res% *}
sw=${res%x*}
sh=${res#*x}
sw=${sw%.*}
sh=${sh%.*}

w=$((sw / 2))
x=$((sw / 2 - w / 2))
y=$((sh / 5))
h=$((sh / 150))

[ "$1" = "run" ] &&
	{ shift ; _run=_run ; }

dmenu${_run} -f -l $h $colors -x $x -y $y -wi $w "$@"
