#!/bin/dash

bat="$(acpi -b | cut -d, -f2 | sed 's/[^0-9]*//g')"
if [ $bat -gt "100" ]; then
	bat = 100
fi

bar=$(/home/raech/.config/scripts/getprogressstring 10 "" "" ${bat})
msgId="991749"
state="$(acpi -b | cut -d: -f2 | cut -d, -f1)"
if [ $state = "Charging" ]; then
	if [ $bat -ge "100" ]; then
		ICON=/home/raech/.config/scripts/icons/full.png
		si=
	else
		ICON=/home/raech/.config/scripts/icons/charging.png
		si=
	fi
else
	if   [ $bat -le "100" ] && [ $bat -gt "75" ]; then
		ICON=/home/raech/.config/scripts/icons/full.png
		si=
	elif [ $bat -le "75" ] && [ $bat -gt "50" ]; then
		ICON=/home/raech/.config/scripts/icons/75bat.png
		si=
	elif [ $bat -le "50" ] && [ $bat -gt "25" ]; then
		ICON=/home/raech/.config/scripts/icons/50bat.png
		si=
	else
		ICON=/home/raech/.config/scripts/icons/10bat.png
		si=
	fi
fi
dunstify -a "changeVolume" -u low -r "$msgId" \  "${si} ${bar} ${bat}%"
#dunstify -a "changeVolume" -u low -i $ICON -r "$msgId" \  "${bar} ${bat}%"
