#!/bin/bash

xbacklight -"$1" 5

if [[ $(printf %0.f $(xbacklight -get)) -eq 0 ]]; then
	xbacklight -set 1
fi
printf %0.f%%\\n $(xbacklight -get)

light="$(xbacklight -get)"
displaylight="${light%.*}"

bar=$(/home/raech/.config/scripts/getprogressstring 10 "" "" ${displaylight})
msgId="912344"

ICON=/home/raech/.config/scripts/icons/brightness.png

dunstify -a "changeVolume" -u low -r "$msgId" \  " ${bar} ${displaylight}%" 
#dunstify -a "changeVolume" -u low -i $ICON -r "$msgId" \  "${bar} ${displaylight}%" 
