#!/bin/bash

if [ "$1" == "manual" ]; then
	mfan=$(cat /sys/devices/platform/applesmc.768/fan1_manual)
	if [ "$mfan" == "0" ]; then
		echo "1" | sudo tee /sys/devices/platform/applesmc.768/fan1_manual
	fi
elif [ "$1" == "speed" ]; then
	cat /sys/devices/platform/applesmc.768/fan1_output
else
	echo "$1" | sudo tee /sys/devices/platform/applesmc.768/fan1_output > /dev/null
fi
