#!/bin/bash

kbdlight "$1" 2

if [[ $(printf %0.f $(kbdlight get)) -eq 0 ]]; then
	kbdlight set 1
fi
printf %0.f%%\\n $(kbdlight get)

light="$(kbdlight get)"
displaylight="${light%.*}"

bar=$(/home/raech/.config/scripts/getprogressstring 10 "" "" ${displaylight})
msgId="912344"

ICON=/home/raech/.config/scripts/icons/brightness.png

dunstify -a "changeVolume" -u low -i $ICON -r "$msgId" \  "${bar} ${displaylight}%" 
