#!/bin/dash

STEP=5
DEFAULTVOLUME=70
MUTED="$(pacmd list-sinks | awk '/muted/ { print $2 }' | grep yes)"

getdefaultsinkname() {
    pacmd stat | awk -F": " '/^Default sink name: /{print $2}'
}

getdefaultsinkvol() {
    pacmd list-sinks |
        awk '/^\s+name: /{indefault = $2 == "<'$(getdefaultsinkname)'>"}
            /^\s+volume: / && indefault {print $5; exit}'

}

setdefaulsinkvol() {
    pactl $(getdefaultsinkname) $1
}




volume=$(expr $(getdefaultsinkvol) | cut -f1 -d "%")

if [ "$1" = "up" ]; then
	if [ "$volume" -gt 99 ]; then
		STEP=0
	fi
	pactl set-sink-mute @DEFAULT_SINK@ 0 && pactl set-sink-volume @DEFAULT_SINK@ +$STEP%
	ICON=/home/raech/.config/scripts/icons/volume.png
	si=
elif [ "$1" = "down" ]; then
	pactl set-sink-mute @DEFAULT_SINK@ 0 && pactl set-sink-volume @DEFAULT_SINK@ -$STEP%
	ICON=/home/raech/.config/scripts/icons/down.png
	si=

elif [ "$1" = "toggle" ]; then
	pactl set-sink-mute @DEFAULT_SINK@ toggle
	#amixer set Master toggle
	if [ "$MUTED" = "yes" ]; then
		ICON=/home/raech/.config/scripts/icons/volume.png
		si=
	else
		ICON=/home/raech/.config/scripts/icons/mute.png
		si=
	fi

elif [ "$1" = "reset" ]; then
	pactl set-sink-mute @DEFAULT_SINK@ 0 && pactl set-sink-volume @DEFAULT_SINK@ $DEFAULTVOLUME%
fi

echo $MUTED


volume=$(expr $(getdefaultsinkvol) | cut -f1 -d "%")
echo $volume

#bar=$(seq --separator="─" 0 "$((volume / 5))" | sed 's/[0-9]//g')
bar=$(/home/raech/.config/scripts/getprogressstring 10 "" "" ${volume})
#bar=$(/home/raech/.config/scripts/getprogressstring 10 "─" " " ${volume})
msgId="991049"

dunstify -a "changeVolume" -u low -r "$msgId" \  "${si} ${bar} ${volume}%"
#dunstify -a "changeVolume" -u low -i $ICON -r "$msgId" \  "${bar} ${volume}%"
