#!/bin/dash

day=`LC_ALL=ja_JP.utf8 date +'%A %b'`
ddate=`date +%H:%M`
msgId="912381"
ICON=/home/raech/.config/scripts/icons/clock.png
dunstify -a "clock_notifier" -u low -r "$msgId" \ "   $ddate        ""$day"
#dunstify -a "clock_notifier" -u low -i $ICON -r "$msgId" \ "$ddate        ""$day"
