#!/bin/fish

# Theme options

set -l curr_theme (cat ~/.Xresources | grep themes | cut -d/ -f 6 | cut -d\" -f 1)
set -l themes (ls ~/.config/themes | menu -p Themes:)

sed -i 's/'$curr_theme'/'$themes'/' ~/.Xresources
xrdb ~/.Xresources


# bspwm borders
set -l bspwm "/home/raech/.config/bspwm/functions/borders"

set -l inner1 (get_xres "color14" | sed 's/#/0x/')
set -l inner2 (get_xres "foreground" | sed 's/#/0x/')
set -l outer (get_xres "background" | sed 's/#/0x/')

set -l foreground (get_xres "foreground")
set -l background (get_xres "background")
set -l focused (get_xres "color14")

sed -i 's/inner1=.*/inner1=\''$inner1'\'/' $bspwm
sed -i 's/inner2=.*/inner2=\''$inner2'\'/' $bspwm
sed -i 's/outer=.*/outer=\''$outer'\'/' $bspwm
sed -i '28s/".*/"'$background'\"/' "/home/raech/.config/bspwm/bspwmrc"
sed -i '29s/".*/"'$background'\"/' "/home/raech/.config/bspwm/bspwmrc"
bspc config normal_border_color $background
bspc config focused_border_color $background

# Vim
#if test $curr_theme = 'FlaredSky'
#	sed -i '9s/set/"\ set/' ~/.vimrc
#	sed -i '10s/colorscheme/"\ colorscheme/' ~/.vimrc
#else
#	sed -i '9s/"\ set/"set/' ~/.vimrc
#	sed -i '10s/"\ colorscheme/"colorscheme/' ~/.vimrc
#end

# Dunst
sed -i 's/background =.*/background = \"'$background'\"/' ~/.config/dunst/dunstrc
sed -i 's/frame_color =.*/frame_color = \"'$focused'\"/' ~/.config/dunst/dunstrc
sed -i 's/foreground =.*/foreground = \"'$foreground'\"/' ~/.config/dunst/dunstrc
# urgency critical, invert colors
sed -i '60s/background =.*/background = \"'$foreground'\"/' ~/.config/dunst/dunstrc
sed -i '61s/foreground =.*/foreground = \"'$background'\"/' ~/.config/dunst/dunstrc

# GTK theme
sed -i '2s/=.*/='$themes'/' ~/.config/gtk-3.0/settings.ini
sed -i '5s/=.*/=\"'$themes'\"/' ~/.gtkrc-2.0

# Disable & Enable programs
pkill -9 dunst; dunst &
pkill -9 borders; exec ~/.config/bspwm/functions/borders &
