#!/bin/dash

STEP=1
DEFAULTVOLUME=70
MUTED="$(pacmd list-sinks | awk '/muted/ { print $2 }' | grep yes)"

if [ "$1" = "up" ]; then
	pactl set-sink-mute @DEFAULT_SINK@ 0 && pactl set-sink-volume @DEFAULT_SINK@ +$STEP%
	ICON=/home/raech/.config/scripts/icons/volume.png
elif [ "$1" = "down" ]; then
	pactl set-sink-mute @DEFAULT_SINK@ 0 && pactl set-sink-volume @DEFAULT_SINK@ -$STEP%
	ICON=/home/raech/.config/scripts/icons/down.png

elif [ "$1" = "toggle" ]; then
	pactl set-sink-mute @DEFAULT_SINK@ toggle
	if [ "$MUTED" == "yes" ]; then
		ICON=/home/raech/.config/scripts/icons/volume.png
	else
		ICON=/home/raech/.config/scripts/icons/mute.png
	fi

elif [ "$1" = "reset" ]; then
	pactl set-sink-mute @DEFAULT_SINK@ 0 && pactl set-sink-volume @DEFAULT_SINK@ $DEFAULTVOLUME%
fi

echo $MUTED

getdefaultsinkname() {
    pacmd stat | awk -F": " '/^Default sink name: /{print $2}'
}

getdefaultsinkvol() {
    pacmd list-sinks |
        awk '/^\s+name: /{indefault = $2 == "<'$(getdefaultsinkname)'>"}
            /^\s+volume: / && indefault {print $5; exit}'

}

setdefaulsinkvol() {
    pactl $(getdefaultsinkname) $1
}


volume=$(expr $(getdefaultsinkvol) | cut -f1 -d "%")

bar=$(/home/raech/.config/scripts/getprogressstring 10 "" "" ${volume})
msgId="991049"

dunstify -a "changeVolume" -u low -i $ICON -r "$msgId" \  "${bar}" 
