#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload
hc set default_layout horizontal

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod4   # Use the super key as the main modifier
Mod=Mod1    # Use alt as the main modifier
Win=Mod4

# Media Keys
hc keybind 0x1008ff13 spawn /home/raech/.config/scripts/volume up
hc keybind 0x1008ff11 spawn /home/raech/.config/scripts/volume down
hc keybind 0x1008ff12 spawn /home/raech/.config/scripts/volume toggle

hc keybind 0x1008ff17 	spawn controlmusic next
hc keybind 0x1008ff16 	spawn controlmusic prev
hc keybind 0x1008ff14 	spawn controlmusic toggle
hc keybind $Mod-comma 	spawn mpc volume -5
hc keybind $Mod-period 	spawn mpc volume +5
hc keybind $Win-m     	spawn mpddunst

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-e reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn st
hc keybind $Mod-r spawn /home/raech/.config/scripts/menu run -p "Run: "
hc keybind $Mod-Print spawn /home/raech/.config/scripts/screenshot.sh -s
hc keybind $Mod-Shift-Print spawn /home/raech/.config/scripts/screenshot.sh -c
hc keybind Print spawn /home/raech/.config/scripts/screenshot.sh
hc keybind $Win-Print spawn /home/raech/.config/scripts/screenshot.sh -b
hc keybind $Win-t spawn /home/raech/.config/scripts/xclock

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( "TERM" "WEB" "MSG" "GAME" "MISC" "MUSIC")
tag_keys=( {1..6} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# custom
#hc load TERM '
#(split horizontal:0.130000:1 (clients vertical:0) (clients horizontal:0 0xc00005))
#'
#hc load WEB '
#(split horizontal:0.130000:1 (clients vertical:0) (clients max:0 0xe00010))
#'
#hc load MSG '
#(split horizontal:0.130000:1 (clients vertical:0) (split vertical:0.900000:0 (split vertical:0.100000:1 (clients vertical:0) (clients vertical:0 0x7800005)) (clients vertical:0)))
#'
#hc load GAME '
#(split horizontal:0.130000:1 (clients vertical:0) (split vertical:0.900000:0 (split vertical:0.100000:1 (clients vertical:0) (clients vertical:0 0x7800005)) (clients vertical:0)))
#'
#hc load MUSIC '
#(split horizontal:0.130000:1 (clients vertical:0) (clients horizontal:0 0xc00005))
#'

# cycle through tags
hc keybind $Mod-x use_index +1 --skip-visible
hc keybind $Mod-z  use_index -1 --skip-visible
hc keybind $Win-period use_index +1 --skip-visible
hc keybind $Win-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-d remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 horizontal max    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button4 use_index +1
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle
hc keybind $Win-Tab cycle
hc keybind $Mod-i jumpto urgent

hc floating GAME on

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
# hc set frame_border_active_color '#34D2AE'
hc set frame_border_active_color '#FAAD45'
hc set frame_border_normal_color '#E12E72'
hc set frame_bg_normal_color ''
hc set frame_bg_active_color '#66000000'
hc set frame_border_width 0
hc set frame_border_inner_width 0
hc set always_show_frame 0
hc set frame_active_opacity 30 
hc set frame_normal_opacity 0 
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 15 

hc attr theme.padding_left 15
hc attr theme.active.color '#FAAD45'
hc attr theme.normal.color '#18859C'
hc attr theme.urgent.color '#FAB148'
hc attr theme.inner_width 0
hc attr theme.outer_witdh 0
hc attr theme.inner_color '#EB9605'
hc attr theme.border_width 5
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color '#FAAD45' 
#hc attr theme.active.inner_color '#FAB148'
#hc attr theme.active.outer_color '#FAB148'
hc attr theme.background_color '#59000000'

hc set window_border_width 0
hc set frame_padding 0
hc set window_gap 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
#hc attr theme.tiling.reset 1
#hc attr theme.floating.reset 1

#hc set frame_border_active_color '#e2a76d'
#hc set frame_border_normal_color '#4ec2e8'
#hc set frame_active_opacity 20
#hc set frame_normal_opacity 0
#hc set frame_bg_transparent 1
#hc set frame_transparent_width 0
#hc set always_show_frame 0
#hc set frame_gap 8
#hc set frame_padding 0
#hc set frame_border_width 2

#hc attr theme.active.color '#e2a76d'
#hc attr theme.normal.color '#2f343f'
#hc attr theme.urgent.color '#f59335'
#hc attr theme.floating.outer_color '#a1d569'
#hc attr theme.border_width 2
#hc attr theme.floating.border_width 2
#hc attr theme.floating.outer_width 0
#hc attr theme.inner_width 1

#hc set window_gap 5
#hc set frame_padding 1
#hc set smart_window_surroundings 1
#hc set smart_frame_surroundings 1
#hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class=Steam tag=GAME
hc rule class=music tag=MUSIC
hc rule class=Firefox tag=WEB
hc rule class=discord tag=MSG
# unlock, just to be sure
hc unlock

herbstclient set tree_style '?| ++?-+'

#############################
# startup
pgrep conky || conky -c ~/.config/conky/conkyrc
pgrep mpd || mpd
pgrep dunst || dunst &
source /home/raech/.fehbg
xcalib -d :0 ~/.config/dell.icc
xinput set-prop 14 'Evdev Scrolling Distance' 1 -10 10
